---
title: "Fluxograma"
author: "Droubi"
date: "19/08/2020"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
library(DiagrammeR)
```

```{r fluxo, echo = FALSE}
DiagrammeR("
graph LR
  A[Abertura do <br> Requerimento] -->|Triagem| B(SPU-SC-NUDEPU)
  B --> C{<center>Caracterização <br> da Área</center>}
  C -->|Área da União| D{<center>Análise Técnica<br><i>Checklist</i></center>}
  C -->|Alodial| N(SPU-SC-NUGES)
  C -->|Mudança de Natureza| R[<center>SPU-UC ou <br> Encaminhar como Cessão</center>]
  D -->|Documentação OK!| E[Elaborar NT e <br> Minuta de Portaria]
  D -->|Documentação incompleta!| M[Elaborar Notificação]
  C -->|Desapropriações e/ou <br> cancelamento de RIPs?| S(SPU-SC-NUPRIV)
  M -->|Tramitação| N
  N -->|Informar| O{Interessado}
  O -->|Ausência de resposta| P(SPU-SC-NUFIS)
  O -->|Resposta| A
  P -->|Infração| Q[Autuação]
  P -->|Sem infração| F
  Q --> F
  E -->|PARA CJU/SC| I{Parecer Jurídico}
  I -->|Favorável| J[Portaria]
  J -->|Assinatura do Superintendente| K[DEDES]
  I -->|Desfavorável| D
  K -->|DOU| L[FIGEST]
  L --> F[FIM!]
")
```

[Fluxograma Marina](fluxogramaAutObras.pdf)